import cs50
import sys
import crypt

def main():
    #make sure there are 2 arguments at command line
    if len(sys.argv) != 2:
        print("Usage: python filename key")
        exit(1)
    
    #Get the hash entered at command line and the salt from userHash
    userHash = sys.argv[1]
    salt = userHash[0:3]
    
    password = crack(userHash, salt)
    
    print(password)
    
    exit(0)
    
def crack(userHash, salt):
    #Stores the hash generated by the crypt function
    gHash = ""
    
    #String we will iterate through
    alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
    length = len(alphabet)
    
    #The attempt we are hashing
    attempt = ["a"]
    
    #Check for a one char password
    for i in range(length):
        #Set the first char
        attempt[0] = alphabet[i]
        
        #Crypt attempt and see if it matches
        sAttempt = ''.join(attempt)
        gHash = crypt.crypt(sAttempt, salt)
        if gHash == userHash:
            return sAttempt
    
    #Grow the list to two and continue
    attempt.append("a")
    
    #Check for two char passwords
    for i in range(length):
        #Set first char
        attempt[0] = alphabet[i]
        for j in range(length):
            #Set second char
            attempt[1] = alphabet[j]
            
            #Crypt attempt and see if it matches
            sAttempt = ''.join(attempt)
            gHash = crypt.crypt(sAttempt, salt)
            if gHash == userHash:
                return sAttempt
                
    #Grow the list to three and continue
    attempt.append("a")
                
    #check for three char passwords
    for i in range(length):
        #Set first char
        attempt[0] = alphabet[i]
        for j in range(length):
            #Set second char
            attempt[1] = alphabet[j]
            for k in range(length):
                #Set third char
                attempt[2] = alphabet[k]
                
                #Crypt attempt and see if it matches
                sAttempt = ''.join(attempt)
                gHash = crypt.crypt(sAttempt, salt)
                if gHash == userHash:
                    return sAttempt
                    
    #Grow the list to four and continue
    attempt.append("a")
                    
    #check for four char passwords
    for i in range(length):
        #Set first char
        attempt[0] = alphabet[i]
        for j in range(length):
            #Set second char
            attempt[1] = alphabet[j]
            for k in range(length):
                #Set third char
                attempt[2] = alphabet[k]
                for l in range(length):
                    #Set fourth char
                    attempt[3] = alphabet[l]
                    
                    #Crypt attempt and see if it matches
                    sAttempt = ''.join(attempt)
                    gHash = crypt.crypt(sAttempt, salt)
                    if gHash == userHash:
                        return sAttempt
                        
    #The password was not found
    return "Password not cracked."

if __name__ == "__main__":
    main()